version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    groups:
      java:
        patterns:
          - "*"
    cooldown:
      default-days: 7

  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: daily
    groups:
      pre-commit:
        patterns:
          - "*"
    cooldown:
      default-days: 7
