rules:
  unpinned-uses:
    ignore:
      - linting.yaml
      - testing.yaml
  anonymous-definition:
    ignore:
      - 'linting.yaml:16'
      - 'linting.yaml:34'
      - 'testing.yaml:22'
  undocumented-permissions:
    ignore: []
