rules:
  unpinned-uses:
    ignore:
      - linting.yaml
      - publishing.yaml
      - testing.yaml
  anonymous-definition:
    ignore:
      - 'linting.yaml:20'
      - 'linting.yaml:37'
      - 'publishing.yaml:15'
      - 'publishing.yaml:35'
      - 'publishing.yaml:55'
      - 'testing.yaml:24'
  undocumented-permissions:
    ignore:
      - 'publishing.yaml:60'
