rules:
  unpinned-uses:
    ignore:
      - linting.yaml
      - testing.yaml
      - publishing.yaml
  anonymous-definition:
    ignore:
      - 'linting.yaml:22'
      - 'publishing.yaml:12'
      - 'publishing.yaml:31'
      - 'publishing.yaml:48'
      - 'publishing.yaml:84'
      - 'testing.yaml:20'
      - 'testing.yaml:47'
  undocumented-permissions:
    ignore:
      - 'publishing.yaml:90'
