name: Publishing
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
env:
  JAVA_VERSION: 17
permissions: {}

jobs:
  build-jar:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - name: Build Shadow JAR
        run: ./gradlew clean shadowJar
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: shadow-jar
          path: build/libs/*.jar

  build-exe:
    permissions:
      contents: read
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@v5.7.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
      - name: Build Windows EXE
        run: ./gradlew clean jpackageWindows
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: windows-exe
          path: build/jpackage/output/*.exe

  release:
    needs:
      - build-jar
      - build-exe
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          name: shadow-jar
          path: artifacts/
      - uses: actions/download-artifact@v8.0.1
        with:
          name: windows-exe
          path: artifacts
      - name: Rename artifacts
        run: |
          mv artifacts/*.jar artifacts/badger.jar
          mv artifacts/*.exe artifacts/badger.exe
      - name: Create Github Release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        run: gh release create $TAG_NAME artifacts/* --title "v$TAG_NAME" --generate-notes
