name: Testing

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.13"
          - "3.14"
        os:
          - ubuntu-latest
          - windows-latest

    permissions:
      contents: read
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6.0.2
      - uses: pdm-project/setup-pdm@v4.5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: pdm install --prod -G test
      - name: Run tests
        run: pdm run pytest

  check:
    if: always()
    needs:
      - pytest
    permissions: {}
    runs-on: ubuntu-latest

    steps:
      - uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
